### ISSUE TITLE
DIYBiook entry not appearing on map

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#232]
Referenced on issue #205. Opening for @DiyBiook 

The entry is not mapped, despite adding geocoordinates by @jasonbobe

**Comment by sabgaby** [comment]
To appear on the map, you have to input geocoordinates in the YAML portion of the entry, which are then transcoded into a `.geojson` file (located in `_site/assets/data/`). 

@jasonbobe... added your geocoordinates at some point, but unfortunately he coded them incorrectly as a _list_ of geocoordinates as in:
```
_geoloc:
  - lat: 43.264988
  - lng: -2.927599 
```
The geojson file interpreted it as `MultiPoint`, with: ` "coordinates": [[, 43.264988], [-2.927599, ]]`
Essentially, neither point was complete, so it didn't map anything. Instead, as I have made the changes myself, the geocoordinates should be coded as a _map_ or _dictionary_, as in:

```
_geoloc:
  lat: 43.264988
  lng: -2.927599 
```
Now the geojson file computes it as a `Point` with `"coordinates": [-2.927599, 43.264988]`
I should upload a fix soon.

**Comment by 100ideas** [comment]
Looks like this is fixed now, so closing.

That said, it's impossible to discover the Biook pin on the map without zooming wayyyy in because the BBK Open Science fest pin sits right on top of it.

Is there a way to add pin-spreading to mapbox?

<img width="499" alt="Screen Shot 2019-05-10 at 5 26 20 PM" src="https://user-images.githubusercontent.com/57006/57562579-e77bca80-7348-11e9-8eaa-29ce12ee099f.png">

<img width="580" alt="Screen Shot 2019-05-10 at 5 26 18 PM" src="https://user-images.githubusercontent.com/57006/57562581-e9de2480-7348-11e9-9b28-dab50c844b7e.png">

<img width="366" alt="Screen Shot 2019-05-10 at 5 26 08 PM" src="https://user-images.githubusercontent.com/57006/57562595-fb273100-7348-11e9-9e33-a1f5f11ca11d.png">
