### ISSUE TITLE
BBK Open Science Festival

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/sphere#233]
Hello @DiyBiook , I opened an [entry for BBK Open Science Festival](https://github.com/diybiosphere/sphere/blob/master/_events/BBKOpenScience/BBKOpenScience.md), the webpage is [this](http://sphere.diybio.org/events/bbkopenscience/). I also added a `promotion` box so there is an advertisement in the landing page. Please feel free to update the file as you wish. 

Please also see how both your entry, and the event are present in the map. If you have any questions or concerns, feel free to ask on [Gitter](https://gitter.im/DIYbiosphere/sphere?utm_source=share-link&utm_medium=link&utm_campaign=share-link), or direct message me there.

**Comment by 100ideas** [comment]
@sabgaby in the future please upload image files and name them 'header' or 'logo' for a given entry. 

this entry was causing rendering problems because the provided image was hosted off-site at twitter and the url was not reliable

see #237 

- good: https://github.com/DIYbiosphere/sphere/tree/7fd113c4d526a33ecdc89740ec8aa14a42cb099f/_events/BBKOpenScience
- not good: https://github.com/DIYbiosphere/sphere/tree/e28022a3ad7218e5302dd6896b52ea636890b137/_events/BBKOpenScience

**Comment by 100ideas** [comment]
since the event has occurred I am going to close this issue.
