### ISSUE TITLE
Put feles on rotating banner on main page

### ISSUE THREAD

**Issue by jasonbobe** [DIYbiosphere/sphere#242]
@100ideas 

How do I put feles on the rotating caurosel on the main page? They have a kickstarter going on now.

https://sphere.diybio.org/startups/feles/

**Comment by YixiaoJ** [comment]
Thanks. Current entry is startups/felesbio/  Can you change it to startups/feles/ 

I also updated images and introduction and sent a pull request, please review and merge.

**Comment by 100ideas** [comment]
fixed in #247 
@YixiaoJ you might want to play around with styling your images some how so they are not so big.

if you add the class `ui fluid image` to them they will resize nicely.

you would have to use html though not the markdown syntax. but that should work ok in the markdown.

like this: <img class="ui fluid image" src="/images/wireframe/image.png">

the site uses semantic-ui css, so you can also use the same trick to apply any other semantic classes to the contents of your page.

https://semantic-ui.com/elements/image.html#floated

**Comment by 100ideas** [comment]
@YixiaoJ nevermind about the img tags, I updated them for you. looks good!

also backed your project.

**Comment by YixiaoJ** [comment]
@100ideas Thanks! You left some really interesting comments. Will get back to you on KS!
